name: catalog_pharmacy_fe
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.1.0
  get: 4.6.6
  google_fonts: ^5.1.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
