// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjob8AUoE7tY_5f9TEkdoPVkcs4mHGZFg',
    appId: '1:378660610904:web:607c1967e517412eb63b2d',
    messagingSenderId: '378660610904',
    projectId: 'catalog-pharmacy',
    authDomain: 'catalog-pharmacy.firebaseapp.com',
    storageBucket: 'catalog-pharmacy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPcqFnCPSjApX3zD8N3SKT55BlI-S1d-o',
    appId: '1:378660610904:android:d82f4095a412b851b63b2d',
    messagingSenderId: '378660610904',
    projectId: 'catalog-pharmacy',
    storageBucket: 'catalog-pharmacy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpYUzDQ7SK_VpZ7ERk9I1vViFcs_5UGh8',
    appId: '1:378660610904:ios:92ae4d560f311ce2b63b2d',
    messagingSenderId: '378660610904',
    projectId: 'catalog-pharmacy',
    storageBucket: 'catalog-pharmacy.appspot.com',
    iosBundleId: 'com.example.catalogPharmacyFe',
  );
}
